### ISSUE TITLE
Price recalculation upon fulfillment

### ISSUE THREAD

**Issue by ashcross** [tasdev-au/craft-fulfillments#10]
I'm getting order prices recalculated by craft commerce after the order has been paid for whenever I create a new fulfillment. This is causing the price status to change to 'overpaid' / 'partially paid' if anything thatimpacts the sale price of an item has changed between the time of purchase and the time of shipment. This is a big problem for us as we allow our customers to view their order history, and they are seeing the items that they purchased change price even though the 'total paid' price remains the same. So none of the lineitems or freight matches up after fulfillment if the rules have changed.

example:
We use promotion > 'sales' quite frequently which changes the price of many products. So say we had a 50% off everything sale being applied, and our customer completes and pays for a product with this sale enabled.
1 week later we disabled the 50% off sale. It takes 2 weeks for us to manufacture the product and then ship it - as soon as the fulfillment tracking code is added to the order, the order recalculates the price and so updates the order to remove the 50% off sale that was originally applied. The customer sees a lineitem in their history of a price that is far more than what they actually paid - and the opposite has also happened.

Recalculating orders that are already completed & paid for is a huge problem. Other things that we have found have affected it:
Updated shipping costs
changing tax rates

**Comment by jaydensmith** [comment]
Hi @ashcross, I have just released a fix for this, thanks.

**Comment by krisMoca** [comment]
Hi Jayden,

Are you sure that the fulfillment plugin does not trigger the recalculation anymore? Attached are screenshots of an order before (order status is processing) and after (order status is Fulfilled) a fulfillment entry. The total price and order status changed once a user creates a fulfillment entry. 

![image](https://user-images.githubusercontent.com/86084360/208538532-43dce007-d4c6-47c5-a6f4-7546377b1a35.png)
![image](https://user-images.githubusercontent.com/86084360/208538476-15455e00-b989-4044-a3bd-59bef1ec4bdc.png)
![image](https://user-images.githubusercontent.com/86084360/208538851-d24ba1f3-85f5-4aac-afdc-d31627776e62.png)

**Comment by jaydensmith** [comment]
@krisMoca the fulfillments plugin updates the order status (fulfilled, partially fulfilled etc.) and saves the order element. I've double checked and the order is not recalculated.

If you have another plugin or custom module that listens on the order save event and does some sort of processing that triggers a recalculation that may be your issue.

If you can list the other plugins you're using and Craft version etc. I can take a closer look for you.

**Comment by krisMoca** [comment]
attached are other plugins used.
![image](https://user-images.githubusercontent.com/86084360/208555618-ee477701-42f7-474f-8a6e-b1b59f38f585.png)

**Comment by jaydensmith** [comment]
@krisMoca do you have any custom modules?

**Comment by krisMoca** [comment]
@jaydensmith yes and debugged it. the plugin is triggering EVENT_BEFORE_SAVE_LINE_ITEM
