### ISSUE TITLE
v5 - beta 2 - Unable to access carriers in the control panel.

### ISSUE THREAD

**Issue by sunscreem** [tasdev-au/craft-fulfillments#15]
I've just upgraded to Craft and Commerce versions 5.

I've installed `v5.0.0-beta.2` and seem to be unable to open the `control panel > settings > fullfilments > carriers` page:

![image](https://github.com/tasdev-au/craft-fulfillments/assets/7523595/3358f916-1e79-4d86-96d2-41c210f7e3d0)

It looks like there is a missing dependency?

<details><summary>Full stack trace here:</summary>
ReflectionException: Class "verbb\formie\web\assets\cp\CpAsset" does not exist in /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php:507
Stack trace:
#0 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/AssetManager.php(292): yii\BaseYii::createObject()
#5 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle()
#6 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/View.php(296): yii\web\AssetManager->getBundle()
#7 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(2106): yii\web\View->registerAssetBundle()
#8 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\web\View->registerAssetBundle()
#9 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/helpers/Template.php(141): twig_get_attribute()
#10 /home/forge/jc.sunscreem.xyz/storage/runtime/compiled_templates/3d/3d5a57bfb68e7f36a787917be40b9765.php(46): craft\helpers\Template::attribute()
#11 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a4078bdd0f77c9a7ab4da162c3a6901b->doDisplay()
#12 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#13 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#14 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#15 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#16 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#17 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate()
#18 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#19 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format()
#20 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#21 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#22 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#23 /home/forge/jc.sunscreem.xyz/web/index.php(14): yii\base\Application->run()
#24 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "verbb\formie\web\assets\cp\CpAsset". in /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php:509
Stack trace:
#0 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#1 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#2 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#3 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/AssetManager.php(292): yii\BaseYii::createObject()
#4 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle()
#5 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/View.php(296): yii\web\AssetManager->getBundle()
#6 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(2106): yii\web\View->registerAssetBundle()
#7 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Extension/CoreExtension.php(1635): craft\web\View->registerAssetBundle()
#8 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/helpers/Template.php(141): twig_get_attribute()
#9 /home/forge/jc.sunscreem.xyz/storage/runtime/compiled_templates/3d/3d5a57bfb68e7f36a787917be40b9765.php(46): craft\helpers\Template::attribute()
#10 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(394): __TwigTemplate_a4078bdd0f77c9a7ab4da162c3a6901b->doDisplay()
#11 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#12 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#13 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#14 /home/forge/jc.sunscreem.xyz/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#15 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#16 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate()
#17 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#18 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/Response.php(1100): craft\web\TemplateResponseFormatter->format()
#19 /home/forge/jc.sunscreem.xyz/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#20 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#21 /home/forge/jc.sunscreem.xyz/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#22 /home/forge/jc.sunscreem.xyz/web/index.php(14): yii\base\Application->run()
#23 {main}
</details>

FYI - The carriers show up correctly in the control panel:

![image](https://github.com/tasdev-au/craft-fulfillments/assets/7523595/4b9ff7f3-b8c0-4da5-81cd-05f7c71048d4)

![image](https://github.com/tasdev-au/craft-fulfillments/assets/7523595/075125a9-e5ba-4161-901b-e08452caa86b)

(That's my screen grab being dumb there - not the drop menu floating in mid air)

**Comment by jaydensmith** [comment]
My bad, should be fixed in the latest release.

**Comment by sunscreem** [comment]
@jaydensmith Perfect - updated and all sorted. :)
