### ISSUE TITLE
Easier configuration of carriers

### ISSUE THREAD

**Issue by mini71** [tasdev-au/craft-fulfillments#4]
Hi, great plugin!
It would be much easier if carriers can be configured via settings or in a config file instead of hardcoded classes.

Regards,
Michael

**Comment by sunscreem** [comment]
@jaydensmith Can I also put a request in for this. Just setting this up a for a client and can't see an easy way to remove the unused shipping methods.

**Comment by Djive** [comment]
Yes that would be great.. or at least support for Postie plugin..  enabled carriers
As there you can make custom carriers..

**Comment by jaydensmith** [comment]
I've released a new version for testing. You will have to update your `composer.json` file to update to this version:

`"tasdev-au/craft-fulfillments": "^4.1.0-beta.1"`

This release will require changes to your email templates. Please check the release notes.
