### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by AndrewMac** [tasdev-au/craft-fulfillments#6]
Hi there

I was just wondering if you had any plans (and/or schedule) to update this for Craft 4?

Cheers, Andrew

**Comment by jaydensmith** [comment]
Hi @AndrewMac, sorry for the delay in getting to this. I have just released version 2.0.0 which addresses this.

**Comment by AndrewMac** [comment]
Hi Jayden
Brilliant, thanks so much!
Cheers, Andrew
