### ISSUE TITLE
Question on creating fulfillment programatically

### ISSUE THREAD

**Issue by idawgik** [tasdev-au/craft-fulfillments#9]
I have a project I'm currently working on where we now need to manage some order updates/fulfillments via an external service (NetSuite). So we're planning out building that integration. I wanted to just clarify what I need to look at to be able to create fulfillments via a plugin instead of the admin.

Any direction on this would be greatly appreciated.

Thank you!

**Comment by jaydensmith** [comment]
@idawgik You're basically trying to replicate what this code does when saving a fulfillment:

https://github.com/tasdev-au/craft-fulfillments/blob/e5349a8b3a235833c230983bf98a4cdc31ddd3cc/src/controllers/FulfillmentsController.php#L128-L167
